# [theme]
# primaryColor = "#00adb5"
# backgroundColor = "#222831"
# secondaryBackgroundColor = "#393e46"
# textColor = "#eeeeee"


[theme]
primaryColor="#d8c4b6"
backgroundColor="#213555"
secondaryBackgroundColor="#3e5879"
textColor="#f5efe7"
